// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/command.proto

package commandpb

import (
	context "context"
	response "github.com/Yeah114/tempest-core/network_api/response"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandService_SendWOCommand_FullMethodName                 = "/fateark.proto.command.CommandService/SendWOCommand"
	CommandService_SendWSCommand_FullMethodName                 = "/fateark.proto.command.CommandService/SendWSCommand"
	CommandService_SendPlayerCommand_FullMethodName             = "/fateark.proto.command.CommandService/SendPlayerCommand"
	CommandService_SendAICommand_FullMethodName                 = "/fateark.proto.command.CommandService/SendAICommand"
	CommandService_SendWSCommandWithResponse_FullMethodName     = "/fateark.proto.command.CommandService/SendWSCommandWithResponse"
	CommandService_SendPlayerCommandWithResponse_FullMethodName = "/fateark.proto.command.CommandService/SendPlayerCommandWithResponse"
	CommandService_SendAICommandWithResponse_FullMethodName     = "/fateark.proto.command.CommandService/SendAICommandWithResponse"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandServiceClient interface {
	SendWOCommand(ctx context.Context, in *SendWOCommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error)
	SendWSCommand(ctx context.Context, in *SendWSCommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error)
	SendPlayerCommand(ctx context.Context, in *SendPlayerCommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error)
	SendAICommand(ctx context.Context, in *SendAICommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error)
	SendWSCommandWithResponse(ctx context.Context, in *SendWSCommandWithResponseRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error)
	SendPlayerCommandWithResponse(ctx context.Context, in *SendPlayerCommandWithResponseRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error)
	SendAICommandWithResponse(ctx context.Context, in *SendAICommandWithResponseRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) SendWOCommand(ctx context.Context, in *SendWOCommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GeneralResponse)
	err := c.cc.Invoke(ctx, CommandService_SendWOCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SendWSCommand(ctx context.Context, in *SendWSCommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GeneralResponse)
	err := c.cc.Invoke(ctx, CommandService_SendWSCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SendPlayerCommand(ctx context.Context, in *SendPlayerCommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GeneralResponse)
	err := c.cc.Invoke(ctx, CommandService_SendPlayerCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SendAICommand(ctx context.Context, in *SendAICommandRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GeneralResponse)
	err := c.cc.Invoke(ctx, CommandService_SendAICommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SendWSCommandWithResponse(ctx context.Context, in *SendWSCommandWithResponseRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GeneralResponse)
	err := c.cc.Invoke(ctx, CommandService_SendWSCommandWithResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SendPlayerCommandWithResponse(ctx context.Context, in *SendPlayerCommandWithResponseRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GeneralResponse)
	err := c.cc.Invoke(ctx, CommandService_SendPlayerCommandWithResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SendAICommandWithResponse(ctx context.Context, in *SendAICommandWithResponseRequest, opts ...grpc.CallOption) (*response.GeneralResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GeneralResponse)
	err := c.cc.Invoke(ctx, CommandService_SendAICommandWithResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility.
type CommandServiceServer interface {
	SendWOCommand(context.Context, *SendWOCommandRequest) (*response.GeneralResponse, error)
	SendWSCommand(context.Context, *SendWSCommandRequest) (*response.GeneralResponse, error)
	SendPlayerCommand(context.Context, *SendPlayerCommandRequest) (*response.GeneralResponse, error)
	SendAICommand(context.Context, *SendAICommandRequest) (*response.GeneralResponse, error)
	SendWSCommandWithResponse(context.Context, *SendWSCommandWithResponseRequest) (*response.GeneralResponse, error)
	SendPlayerCommandWithResponse(context.Context, *SendPlayerCommandWithResponseRequest) (*response.GeneralResponse, error)
	SendAICommandWithResponse(context.Context, *SendAICommandWithResponseRequest) (*response.GeneralResponse, error)
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServiceServer struct{}

func (UnimplementedCommandServiceServer) SendWOCommand(context.Context, *SendWOCommandRequest) (*response.GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWOCommand not implemented")
}
func (UnimplementedCommandServiceServer) SendWSCommand(context.Context, *SendWSCommandRequest) (*response.GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWSCommand not implemented")
}
func (UnimplementedCommandServiceServer) SendPlayerCommand(context.Context, *SendPlayerCommandRequest) (*response.GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPlayerCommand not implemented")
}
func (UnimplementedCommandServiceServer) SendAICommand(context.Context, *SendAICommandRequest) (*response.GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAICommand not implemented")
}
func (UnimplementedCommandServiceServer) SendWSCommandWithResponse(context.Context, *SendWSCommandWithResponseRequest) (*response.GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWSCommandWithResponse not implemented")
}
func (UnimplementedCommandServiceServer) SendPlayerCommandWithResponse(context.Context, *SendPlayerCommandWithResponseRequest) (*response.GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPlayerCommandWithResponse not implemented")
}
func (UnimplementedCommandServiceServer) SendAICommandWithResponse(context.Context, *SendAICommandWithResponseRequest) (*response.GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAICommandWithResponse not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}
func (UnimplementedCommandServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_SendWOCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWOCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendWOCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendWOCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendWOCommand(ctx, req.(*SendWOCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SendWSCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWSCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendWSCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendWSCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendWSCommand(ctx, req.(*SendWSCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SendPlayerCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPlayerCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendPlayerCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendPlayerCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendPlayerCommand(ctx, req.(*SendPlayerCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SendAICommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAICommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendAICommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendAICommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendAICommand(ctx, req.(*SendAICommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SendWSCommandWithResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWSCommandWithResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendWSCommandWithResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendWSCommandWithResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendWSCommandWithResponse(ctx, req.(*SendWSCommandWithResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SendPlayerCommandWithResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPlayerCommandWithResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendPlayerCommandWithResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendPlayerCommandWithResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendPlayerCommandWithResponse(ctx, req.(*SendPlayerCommandWithResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SendAICommandWithResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAICommandWithResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SendAICommandWithResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SendAICommandWithResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SendAICommandWithResponse(ctx, req.(*SendAICommandWithResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fateark.proto.command.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWOCommand",
			Handler:    _CommandService_SendWOCommand_Handler,
		},
		{
			MethodName: "SendWSCommand",
			Handler:    _CommandService_SendWSCommand_Handler,
		},
		{
			MethodName: "SendPlayerCommand",
			Handler:    _CommandService_SendPlayerCommand_Handler,
		},
		{
			MethodName: "SendAICommand",
			Handler:    _CommandService_SendAICommand_Handler,
		},
		{
			MethodName: "SendWSCommandWithResponse",
			Handler:    _CommandService_SendWSCommandWithResponse_Handler,
		},
		{
			MethodName: "SendPlayerCommandWithResponse",
			Handler:    _CommandService_SendPlayerCommandWithResponse_Handler,
		},
		{
			MethodName: "SendAICommandWithResponse",
			Handler:    _CommandService_SendAICommandWithResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/command.proto",
}
