// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/command.proto

package commandpb

import (
	response "github.com/Yeah114/tempest-core/network_api/response"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendWOCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWOCommandRequest) Reset() {
	*x = SendWOCommandRequest{}
	mi := &file_proto_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWOCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWOCommandRequest) ProtoMessage() {}

func (x *SendWOCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWOCommandRequest.ProtoReflect.Descriptor instead.
func (*SendWOCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{0}
}

func (x *SendWOCommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type SendWSCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWSCommandRequest) Reset() {
	*x = SendWSCommandRequest{}
	mi := &file_proto_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWSCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWSCommandRequest) ProtoMessage() {}

func (x *SendWSCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWSCommandRequest.ProtoReflect.Descriptor instead.
func (*SendWSCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{1}
}

func (x *SendWSCommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type SendPlayerCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerCommandRequest) Reset() {
	*x = SendPlayerCommandRequest{}
	mi := &file_proto_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerCommandRequest) ProtoMessage() {}

func (x *SendPlayerCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerCommandRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{2}
}

func (x *SendPlayerCommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type SendAICommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAICommandRequest) Reset() {
	*x = SendAICommandRequest{}
	mi := &file_proto_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAICommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAICommandRequest) ProtoMessage() {}

func (x *SendAICommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAICommandRequest.ProtoReflect.Descriptor instead.
func (*SendAICommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{3}
}

func (x *SendAICommandRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *SendAICommandRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type SendWSCommandWithResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWSCommandWithResponseRequest) Reset() {
	*x = SendWSCommandWithResponseRequest{}
	mi := &file_proto_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWSCommandWithResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWSCommandWithResponseRequest) ProtoMessage() {}

func (x *SendWSCommandWithResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWSCommandWithResponseRequest.ProtoReflect.Descriptor instead.
func (*SendWSCommandWithResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{4}
}

func (x *SendWSCommandWithResponseRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type SendPlayerCommandWithResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerCommandWithResponseRequest) Reset() {
	*x = SendPlayerCommandWithResponseRequest{}
	mi := &file_proto_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerCommandWithResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerCommandWithResponseRequest) ProtoMessage() {}

func (x *SendPlayerCommandWithResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerCommandWithResponseRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerCommandWithResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{5}
}

func (x *SendPlayerCommandWithResponseRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type SendAICommandWithResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAICommandWithResponseRequest) Reset() {
	*x = SendAICommandWithResponseRequest{}
	mi := &file_proto_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAICommandWithResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAICommandWithResponseRequest) ProtoMessage() {}

func (x *SendAICommandWithResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAICommandWithResponseRequest.ProtoReflect.Descriptor instead.
func (*SendAICommandWithResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_command_proto_rawDescGZIP(), []int{6}
}

func (x *SendAICommandWithResponseRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *SendAICommandWithResponseRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

var File_proto_command_proto protoreflect.FileDescriptor

const file_proto_command_proto_rawDesc = "" +
	"\n" +
	"\x13proto/command.proto\x12\x15fateark.proto.command\x1a\x14proto/response.proto\"(\n" +
	"\x14SendWOCommandRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"(\n" +
	"\x14SendWSCommandRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\",\n" +
	"\x18SendPlayerCommandRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"G\n" +
	"\x14SendAICommandRequest\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\"4\n" +
	" SendWSCommandWithResponseRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"8\n" +
	"$SendPlayerCommandWithResponseRequest\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"S\n" +
	" SendAICommandWithResponseRequest\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd2\xba\x06\n" +
	"\x0eCommandService\x12e\n" +
	"\rSendWOCommand\x12+.fateark.proto.command.SendWOCommandRequest\x1a'.fateark.proto.response.GeneralResponse\x12e\n" +
	"\rSendWSCommand\x12+.fateark.proto.command.SendWSCommandRequest\x1a'.fateark.proto.response.GeneralResponse\x12m\n" +
	"\x11SendPlayerCommand\x12/.fateark.proto.command.SendPlayerCommandRequest\x1a'.fateark.proto.response.GeneralResponse\x12e\n" +
	"\rSendAICommand\x12+.fateark.proto.command.SendAICommandRequest\x1a'.fateark.proto.response.GeneralResponse\x12}\n" +
	"\x19SendWSCommandWithResponse\x127.fateark.proto.command.SendWSCommandWithResponseRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x85\x01\n" +
	"\x1dSendPlayerCommandWithResponse\x12;.fateark.proto.command.SendPlayerCommandWithResponseRequest\x1a'.fateark.proto.response.GeneralResponse\x12}\n" +
	"\x19SendAICommandWithResponse\x127.fateark.proto.command.SendAICommandWithResponseRequest\x1a'.fateark.proto.response.GeneralResponseB?Z=github.com/Yeah114/tempest-core/network_api/command;commandpbb\x06proto3"

var (
	file_proto_command_proto_rawDescOnce sync.Once
	file_proto_command_proto_rawDescData []byte
)

func file_proto_command_proto_rawDescGZIP() []byte {
	file_proto_command_proto_rawDescOnce.Do(func() {
		file_proto_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)))
	})
	return file_proto_command_proto_rawDescData
}

var file_proto_command_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_command_proto_goTypes = []any{
	(*SendWOCommandRequest)(nil),                 // 0: fateark.proto.command.SendWOCommandRequest
	(*SendWSCommandRequest)(nil),                 // 1: fateark.proto.command.SendWSCommandRequest
	(*SendPlayerCommandRequest)(nil),             // 2: fateark.proto.command.SendPlayerCommandRequest
	(*SendAICommandRequest)(nil),                 // 3: fateark.proto.command.SendAICommandRequest
	(*SendWSCommandWithResponseRequest)(nil),     // 4: fateark.proto.command.SendWSCommandWithResponseRequest
	(*SendPlayerCommandWithResponseRequest)(nil), // 5: fateark.proto.command.SendPlayerCommandWithResponseRequest
	(*SendAICommandWithResponseRequest)(nil),     // 6: fateark.proto.command.SendAICommandWithResponseRequest
	(*response.GeneralResponse)(nil),             // 7: fateark.proto.response.GeneralResponse
}
var file_proto_command_proto_depIdxs = []int32{
	0, // 0: fateark.proto.command.CommandService.SendWOCommand:input_type -> fateark.proto.command.SendWOCommandRequest
	1, // 1: fateark.proto.command.CommandService.SendWSCommand:input_type -> fateark.proto.command.SendWSCommandRequest
	2, // 2: fateark.proto.command.CommandService.SendPlayerCommand:input_type -> fateark.proto.command.SendPlayerCommandRequest
	3, // 3: fateark.proto.command.CommandService.SendAICommand:input_type -> fateark.proto.command.SendAICommandRequest
	4, // 4: fateark.proto.command.CommandService.SendWSCommandWithResponse:input_type -> fateark.proto.command.SendWSCommandWithResponseRequest
	5, // 5: fateark.proto.command.CommandService.SendPlayerCommandWithResponse:input_type -> fateark.proto.command.SendPlayerCommandWithResponseRequest
	6, // 6: fateark.proto.command.CommandService.SendAICommandWithResponse:input_type -> fateark.proto.command.SendAICommandWithResponseRequest
	7, // 7: fateark.proto.command.CommandService.SendWOCommand:output_type -> fateark.proto.response.GeneralResponse
	7, // 8: fateark.proto.command.CommandService.SendWSCommand:output_type -> fateark.proto.response.GeneralResponse
	7, // 9: fateark.proto.command.CommandService.SendPlayerCommand:output_type -> fateark.proto.response.GeneralResponse
	7, // 10: fateark.proto.command.CommandService.SendAICommand:output_type -> fateark.proto.response.GeneralResponse
	7, // 11: fateark.proto.command.CommandService.SendWSCommandWithResponse:output_type -> fateark.proto.response.GeneralResponse
	7, // 12: fateark.proto.command.CommandService.SendPlayerCommandWithResponse:output_type -> fateark.proto.response.GeneralResponse
	7, // 13: fateark.proto.command.CommandService.SendAICommandWithResponse:output_type -> fateark.proto.response.GeneralResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_command_proto_init() }
func file_proto_command_proto_init() {
	if File_proto_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_command_proto_rawDesc), len(file_proto_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_command_proto_goTypes,
		DependencyIndexes: file_proto_command_proto_depIdxs,
		MessageInfos:      file_proto_command_proto_msgTypes,
	}.Build()
	File_proto_command_proto = out.File
	file_proto_command_proto_goTypes = nil
	file_proto_command_proto_depIdxs = nil
}
