// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/reversaler.proto

package reversalerpb

import (
	response "github.com/Yeah114/tempest-core/network_api/response"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewFateReversalerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthServer     string                 `protobuf:"bytes,1,opt,name=auth_server,json=authServer,proto3" json:"auth_server,omitempty"`
	UserName       string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword   string                 `protobuf:"bytes,3,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	UserToken      string                 `protobuf:"bytes,4,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	ServerCode     string                 `protobuf:"bytes,5,opt,name=server_code,json=serverCode,proto3" json:"server_code,omitempty"`
	ServerPassword string                 `protobuf:"bytes,6,opt,name=server_password,json=serverPassword,proto3" json:"server_password,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewFateReversalerRequest) Reset() {
	*x = NewFateReversalerRequest{}
	mi := &file_proto_reversaler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFateReversalerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFateReversalerRequest) ProtoMessage() {}

func (x *NewFateReversalerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reversaler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFateReversalerRequest.ProtoReflect.Descriptor instead.
func (*NewFateReversalerRequest) Descriptor() ([]byte, []int) {
	return file_proto_reversaler_proto_rawDescGZIP(), []int{0}
}

func (x *NewFateReversalerRequest) GetAuthServer() string {
	if x != nil {
		return x.AuthServer
	}
	return ""
}

func (x *NewFateReversalerRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *NewFateReversalerRequest) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *NewFateReversalerRequest) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *NewFateReversalerRequest) GetServerCode() string {
	if x != nil {
		return x.ServerCode
	}
	return ""
}

func (x *NewFateReversalerRequest) GetServerPassword() string {
	if x != nil {
		return x.ServerPassword
	}
	return ""
}

type WaitDeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitDeadRequest) Reset() {
	*x = WaitDeadRequest{}
	mi := &file_proto_reversaler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitDeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitDeadRequest) ProtoMessage() {}

func (x *WaitDeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reversaler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitDeadRequest.ProtoReflect.Descriptor instead.
func (*WaitDeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_reversaler_proto_rawDescGZIP(), []int{1}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_reversaler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reversaler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_reversaler_proto_rawDescGZIP(), []int{2}
}

var File_proto_reversaler_proto protoreflect.FileDescriptor

const file_proto_reversaler_proto_rawDesc = "" +
	"\n" +
	"\x16proto/reversaler.proto\x12\x18fateark.proto.reversaler\x1a\x14proto/response.proto\"\xe6\x01\n" +
	"\x18NewFateReversalerRequest\x12\x1f\n" +
	"\vauth_server\x18\x01 \x01(\tR\n" +
	"authServer\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12#\n" +
	"\ruser_password\x18\x03 \x01(\tR\fuserPassword\x12\x1d\n" +
	"\n" +
	"user_token\x18\x04 \x01(\tR\tuserToken\x12\x1f\n" +
	"\vserver_code\x18\x05 \x01(\tR\n" +
	"serverCode\x12'\n" +
	"\x0fserver_password\x18\x06 \x01(\tR\x0eserverPassword\"\x11\n" +
	"\x0fWaitDeadRequest\"\r\n" +
	"\vPingRequest2\xbb\x02\n" +
	"\x15FateReversalerService\x12p\n" +
	"\x11NewFateReversaler\x122.fateark.proto.reversaler.NewFateReversalerRequest\x1a'.fateark.proto.response.GeneralResponse\x12[\n" +
	"\bWaitDead\x12).fateark.proto.reversaler.WaitDeadRequest\x1a\".fateark.proto.response.DeadReason0\x01\x12S\n" +
	"\x04Ping\x12%.fateark.proto.reversaler.PingRequest\x1a$.fateark.proto.response.PingResponseBEZCgithub.com/Yeah114/tempest-core/network_api/reversaler;reversalerpbb\x06proto3"

var (
	file_proto_reversaler_proto_rawDescOnce sync.Once
	file_proto_reversaler_proto_rawDescData []byte
)

func file_proto_reversaler_proto_rawDescGZIP() []byte {
	file_proto_reversaler_proto_rawDescOnce.Do(func() {
		file_proto_reversaler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reversaler_proto_rawDesc), len(file_proto_reversaler_proto_rawDesc)))
	})
	return file_proto_reversaler_proto_rawDescData
}

var file_proto_reversaler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_reversaler_proto_goTypes = []any{
	(*NewFateReversalerRequest)(nil), // 0: fateark.proto.reversaler.NewFateReversalerRequest
	(*WaitDeadRequest)(nil),          // 1: fateark.proto.reversaler.WaitDeadRequest
	(*PingRequest)(nil),              // 2: fateark.proto.reversaler.PingRequest
	(*response.GeneralResponse)(nil), // 3: fateark.proto.response.GeneralResponse
	(*response.DeadReason)(nil),      // 4: fateark.proto.response.DeadReason
	(*response.PingResponse)(nil),    // 5: fateark.proto.response.PingResponse
}
var file_proto_reversaler_proto_depIdxs = []int32{
	0, // 0: fateark.proto.reversaler.FateReversalerService.NewFateReversaler:input_type -> fateark.proto.reversaler.NewFateReversalerRequest
	1, // 1: fateark.proto.reversaler.FateReversalerService.WaitDead:input_type -> fateark.proto.reversaler.WaitDeadRequest
	2, // 2: fateark.proto.reversaler.FateReversalerService.Ping:input_type -> fateark.proto.reversaler.PingRequest
	3, // 3: fateark.proto.reversaler.FateReversalerService.NewFateReversaler:output_type -> fateark.proto.response.GeneralResponse
	4, // 4: fateark.proto.reversaler.FateReversalerService.WaitDead:output_type -> fateark.proto.response.DeadReason
	5, // 5: fateark.proto.reversaler.FateReversalerService.Ping:output_type -> fateark.proto.response.PingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reversaler_proto_init() }
func file_proto_reversaler_proto_init() {
	if File_proto_reversaler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reversaler_proto_rawDesc), len(file_proto_reversaler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reversaler_proto_goTypes,
		DependencyIndexes: file_proto_reversaler_proto_depIdxs,
		MessageInfos:      file_proto_reversaler_proto_msgTypes,
	}.Build()
	File_proto_reversaler_proto = out.File
	file_proto_reversaler_proto_goTypes = nil
	file_proto_reversaler_proto_depIdxs = nil
}
