// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/listener.proto

package listenerpb

import (
	response "github.com/Yeah114/tempest-core/network_api/response"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenFateArkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenFateArkRequest) Reset() {
	*x = ListenFateArkRequest{}
	mi := &file_proto_listener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenFateArkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenFateArkRequest) ProtoMessage() {}

func (x *ListenFateArkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenFateArkRequest.ProtoReflect.Descriptor instead.
func (*ListenFateArkRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{0}
}

type ListenPacketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenPacketsRequest) Reset() {
	*x = ListenPacketsRequest{}
	mi := &file_proto_listener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenPacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenPacketsRequest) ProtoMessage() {}

func (x *ListenPacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenPacketsRequest.ProtoReflect.Descriptor instead.
func (*ListenPacketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{1}
}

type ListenBytesPacketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenBytesPacketsRequest) Reset() {
	*x = ListenBytesPacketsRequest{}
	mi := &file_proto_listener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenBytesPacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenBytesPacketsRequest) ProtoMessage() {}

func (x *ListenBytesPacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenBytesPacketsRequest.ProtoReflect.Descriptor instead.
func (*ListenBytesPacketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{2}
}

type ListenTypedPacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      uint32                 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenTypedPacketRequest) Reset() {
	*x = ListenTypedPacketRequest{}
	mi := &file_proto_listener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenTypedPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenTypedPacketRequest) ProtoMessage() {}

func (x *ListenTypedPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenTypedPacketRequest.ProtoReflect.Descriptor instead.
func (*ListenTypedPacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{3}
}

func (x *ListenTypedPacketRequest) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

type ListenTypedBytesPacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      uint32                 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenTypedBytesPacketRequest) Reset() {
	*x = ListenTypedBytesPacketRequest{}
	mi := &file_proto_listener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenTypedBytesPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenTypedBytesPacketRequest) ProtoMessage() {}

func (x *ListenTypedBytesPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenTypedBytesPacketRequest.ProtoReflect.Descriptor instead.
func (*ListenTypedBytesPacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{4}
}

func (x *ListenTypedBytesPacketRequest) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

type ListenPlayerChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenPlayerChangeRequest) Reset() {
	*x = ListenPlayerChangeRequest{}
	mi := &file_proto_listener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenPlayerChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenPlayerChangeRequest) ProtoMessage() {}

func (x *ListenPlayerChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenPlayerChangeRequest.ProtoReflect.Descriptor instead.
func (*ListenPlayerChangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{5}
}

type ListenChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenChatRequest) Reset() {
	*x = ListenChatRequest{}
	mi := &file_proto_listener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenChatRequest) ProtoMessage() {}

func (x *ListenChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenChatRequest.ProtoReflect.Descriptor instead.
func (*ListenChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{6}
}

type ListenCommandBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenCommandBlockRequest) Reset() {
	*x = ListenCommandBlockRequest{}
	mi := &file_proto_listener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenCommandBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenCommandBlockRequest) ProtoMessage() {}

func (x *ListenCommandBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenCommandBlockRequest.ProtoReflect.Descriptor instead.
func (*ListenCommandBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{7}
}

func (x *ListenCommandBlockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       string                 `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_proto_listener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{8}
}

func (x *Output) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *Output) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Output) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_proto_listener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{9}
}

func (x *Packet) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Packet) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type BytesPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesPacket) Reset() {
	*x = BytesPacket{}
	mi := &file_proto_listener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesPacket) ProtoMessage() {}

func (x *BytesPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesPacket.ProtoReflect.Descriptor instead.
func (*BytesPacket) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{10}
}

func (x *BytesPacket) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BytesPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PlayerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_proto_listener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_proto_listener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_listener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_listener_proto_rawDescGZIP(), []int{12}
}

func (x *Chat) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_proto_listener_proto protoreflect.FileDescriptor

const file_proto_listener_proto_rawDesc = "" +
	"\n" +
	"\x14proto/listener.proto\x12\x16fateark.proto.listener\x1a\x14proto/response.proto\"\x16\n" +
	"\x14ListenFateArkRequest\"\x16\n" +
	"\x14ListenPacketsRequest\"\x1b\n" +
	"\x19ListenBytesPacketsRequest\"7\n" +
	"\x18ListenTypedPacketRequest\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\rR\bpacketId\"<\n" +
	"\x1dListenTypedBytesPacketRequest\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\rR\bpacketId\"\x1b\n" +
	"\x19ListenPlayerChangeRequest\"\x13\n" +
	"\x11ListenChatRequest\"/\n" +
	"\x19ListenCommandBlockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"N\n" +
	"\x06Output\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\tR\amsgType\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\aerr_msg\x18\x03 \x01(\tR\x06errMsg\"2\n" +
	"\x06Packet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"7\n" +
	"\vBytesPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"&\n" +
	"\fPlayerAction\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\" \n" +
	"\x04Chat\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload2\xe0\x06\n" +
	"\x0fListenerService\x12_\n" +
	"\rListenFateArk\x12,.fateark.proto.listener.ListenFateArkRequest\x1a\x1e.fateark.proto.listener.Output0\x01\x12_\n" +
	"\rListenPackets\x12,.fateark.proto.listener.ListenPacketsRequest\x1a\x1e.fateark.proto.listener.Packet0\x01\x12n\n" +
	"\x12ListenBytesPackets\x121.fateark.proto.listener.ListenBytesPacketsRequest\x1a#.fateark.proto.listener.BytesPacket0\x01\x12n\n" +
	"\x11ListenTypedPacket\x120.fateark.proto.listener.ListenTypedPacketRequest\x1a'.fateark.proto.response.GeneralResponse\x12x\n" +
	"\x16ListenTypedBytesPacket\x125.fateark.proto.listener.ListenTypedBytesPacketRequest\x1a'.fateark.proto.response.GeneralResponse\x12o\n" +
	"\x12ListenPlayerChange\x121.fateark.proto.listener.ListenPlayerChangeRequest\x1a$.fateark.proto.listener.PlayerAction0\x01\x12W\n" +
	"\n" +
	"ListenChat\x12).fateark.proto.listener.ListenChatRequest\x1a\x1c.fateark.proto.listener.Chat0\x01\x12g\n" +
	"\x12ListenCommandBlock\x121.fateark.proto.listener.ListenCommandBlockRequest\x1a\x1c.fateark.proto.listener.Chat0\x01BAZ?github.com/Yeah114/tempest-core/network_api/listener;listenerpbb\x06proto3"

var (
	file_proto_listener_proto_rawDescOnce sync.Once
	file_proto_listener_proto_rawDescData []byte
)

func file_proto_listener_proto_rawDescGZIP() []byte {
	file_proto_listener_proto_rawDescOnce.Do(func() {
		file_proto_listener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_listener_proto_rawDesc), len(file_proto_listener_proto_rawDesc)))
	})
	return file_proto_listener_proto_rawDescData
}

var file_proto_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_listener_proto_goTypes = []any{
	(*ListenFateArkRequest)(nil),          // 0: fateark.proto.listener.ListenFateArkRequest
	(*ListenPacketsRequest)(nil),          // 1: fateark.proto.listener.ListenPacketsRequest
	(*ListenBytesPacketsRequest)(nil),     // 2: fateark.proto.listener.ListenBytesPacketsRequest
	(*ListenTypedPacketRequest)(nil),      // 3: fateark.proto.listener.ListenTypedPacketRequest
	(*ListenTypedBytesPacketRequest)(nil), // 4: fateark.proto.listener.ListenTypedBytesPacketRequest
	(*ListenPlayerChangeRequest)(nil),     // 5: fateark.proto.listener.ListenPlayerChangeRequest
	(*ListenChatRequest)(nil),             // 6: fateark.proto.listener.ListenChatRequest
	(*ListenCommandBlockRequest)(nil),     // 7: fateark.proto.listener.ListenCommandBlockRequest
	(*Output)(nil),                        // 8: fateark.proto.listener.Output
	(*Packet)(nil),                        // 9: fateark.proto.listener.Packet
	(*BytesPacket)(nil),                   // 10: fateark.proto.listener.BytesPacket
	(*PlayerAction)(nil),                  // 11: fateark.proto.listener.PlayerAction
	(*Chat)(nil),                          // 12: fateark.proto.listener.Chat
	(*response.GeneralResponse)(nil),      // 13: fateark.proto.response.GeneralResponse
}
var file_proto_listener_proto_depIdxs = []int32{
	0,  // 0: fateark.proto.listener.ListenerService.ListenFateArk:input_type -> fateark.proto.listener.ListenFateArkRequest
	1,  // 1: fateark.proto.listener.ListenerService.ListenPackets:input_type -> fateark.proto.listener.ListenPacketsRequest
	2,  // 2: fateark.proto.listener.ListenerService.ListenBytesPackets:input_type -> fateark.proto.listener.ListenBytesPacketsRequest
	3,  // 3: fateark.proto.listener.ListenerService.ListenTypedPacket:input_type -> fateark.proto.listener.ListenTypedPacketRequest
	4,  // 4: fateark.proto.listener.ListenerService.ListenTypedBytesPacket:input_type -> fateark.proto.listener.ListenTypedBytesPacketRequest
	5,  // 5: fateark.proto.listener.ListenerService.ListenPlayerChange:input_type -> fateark.proto.listener.ListenPlayerChangeRequest
	6,  // 6: fateark.proto.listener.ListenerService.ListenChat:input_type -> fateark.proto.listener.ListenChatRequest
	7,  // 7: fateark.proto.listener.ListenerService.ListenCommandBlock:input_type -> fateark.proto.listener.ListenCommandBlockRequest
	8,  // 8: fateark.proto.listener.ListenerService.ListenFateArk:output_type -> fateark.proto.listener.Output
	9,  // 9: fateark.proto.listener.ListenerService.ListenPackets:output_type -> fateark.proto.listener.Packet
	10, // 10: fateark.proto.listener.ListenerService.ListenBytesPackets:output_type -> fateark.proto.listener.BytesPacket
	13, // 11: fateark.proto.listener.ListenerService.ListenTypedPacket:output_type -> fateark.proto.response.GeneralResponse
	13, // 12: fateark.proto.listener.ListenerService.ListenTypedBytesPacket:output_type -> fateark.proto.response.GeneralResponse
	11, // 13: fateark.proto.listener.ListenerService.ListenPlayerChange:output_type -> fateark.proto.listener.PlayerAction
	12, // 14: fateark.proto.listener.ListenerService.ListenChat:output_type -> fateark.proto.listener.Chat
	12, // 15: fateark.proto.listener.ListenerService.ListenCommandBlock:output_type -> fateark.proto.listener.Chat
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_listener_proto_init() }
func file_proto_listener_proto_init() {
	if File_proto_listener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_listener_proto_rawDesc), len(file_proto_listener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_listener_proto_goTypes,
		DependencyIndexes: file_proto_listener_proto_depIdxs,
		MessageInfos:      file_proto_listener_proto_msgTypes,
	}.Build()
	File_proto_listener_proto = out.File
	file_proto_listener_proto_goTypes = nil
	file_proto_listener_proto_depIdxs = nil
}
