// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/utils.proto

package utilspb

import (
	response "github.com/Yeah114/tempest-core/network_api/response"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      int32                  `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	JsonStr       string                 `protobuf:"bytes,2,opt,name=json_str,json=jsonStr,proto3" json:"json_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPacketRequest) Reset() {
	*x = SendPacketRequest{}
	mi := &file_proto_utils_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPacketRequest) ProtoMessage() {}

func (x *SendPacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_utils_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPacketRequest.ProtoReflect.Descriptor instead.
func (*SendPacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_utils_proto_rawDescGZIP(), []int{0}
}

func (x *SendPacketRequest) GetPacketId() int32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *SendPacketRequest) GetJsonStr() string {
	if x != nil {
		return x.JsonStr
	}
	return ""
}

type SendBytePacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      int32                  `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBytePacketRequest) Reset() {
	*x = SendBytePacketRequest{}
	mi := &file_proto_utils_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBytePacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBytePacketRequest) ProtoMessage() {}

func (x *SendBytePacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_utils_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBytePacketRequest.ProtoReflect.Descriptor instead.
func (*SendBytePacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_utils_proto_rawDescGZIP(), []int{1}
}

func (x *SendBytePacketRequest) GetPacketId() int32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *SendBytePacketRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetPacketNameIDMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPacketNameIDMappingRequest) Reset() {
	*x = GetPacketNameIDMappingRequest{}
	mi := &file_proto_utils_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPacketNameIDMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPacketNameIDMappingRequest) ProtoMessage() {}

func (x *GetPacketNameIDMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_utils_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPacketNameIDMappingRequest.ProtoReflect.Descriptor instead.
func (*GetPacketNameIDMappingRequest) Descriptor() ([]byte, []int) {
	return file_proto_utils_proto_rawDescGZIP(), []int{2}
}

type GetClientMaintainedBotBasicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientMaintainedBotBasicInfoRequest) Reset() {
	*x = GetClientMaintainedBotBasicInfoRequest{}
	mi := &file_proto_utils_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientMaintainedBotBasicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientMaintainedBotBasicInfoRequest) ProtoMessage() {}

func (x *GetClientMaintainedBotBasicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_utils_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientMaintainedBotBasicInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClientMaintainedBotBasicInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_utils_proto_rawDescGZIP(), []int{3}
}

type GetClientMaintainedExtendInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientMaintainedExtendInfoRequest) Reset() {
	*x = GetClientMaintainedExtendInfoRequest{}
	mi := &file_proto_utils_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientMaintainedExtendInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientMaintainedExtendInfoRequest) ProtoMessage() {}

func (x *GetClientMaintainedExtendInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_utils_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientMaintainedExtendInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClientMaintainedExtendInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_utils_proto_rawDescGZIP(), []int{4}
}

var File_proto_utils_proto protoreflect.FileDescriptor

const file_proto_utils_proto_rawDesc = "" +
	"\n" +
	"\x11proto/utils.proto\x12\x13fateark.proto.utils\x1a\x14proto/response.proto\"K\n" +
	"\x11SendPacketRequest\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\x05R\bpacketId\x12\x19\n" +
	"\bjson_str\x18\x02 \x01(\tR\ajsonStr\"N\n" +
	"\x15SendBytePacketRequest\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\x05R\bpacketId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x1f\n" +
	"\x1dGetPacketNameIDMappingRequest\"(\n" +
	"&GetClientMaintainedBotBasicInfoRequest\"&\n" +
	"$GetClientMaintainedExtendInfoRequest2\xdb\x04\n" +
	"\fUtilsService\x12]\n" +
	"\n" +
	"SendPacket\x12&.fateark.proto.utils.SendPacketRequest\x1a'.fateark.proto.response.GeneralResponse\x12e\n" +
	"\x0eSendBytePacket\x12*.fateark.proto.utils.SendBytePacketRequest\x1a'.fateark.proto.response.GeneralResponse\x12u\n" +
	"\x16GetPacketNameIDMapping\x122.fateark.proto.utils.GetPacketNameIDMappingRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x87\x01\n" +
	"\x1fGetClientMaintainedBotBasicInfo\x12;.fateark.proto.utils.GetClientMaintainedBotBasicInfoRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x83\x01\n" +
	"\x1dGetClientMaintainedExtendInfo\x129.fateark.proto.utils.GetClientMaintainedExtendInfoRequest\x1a'.fateark.proto.response.GeneralResponseB;Z9github.com/Yeah114/tempest-core/network_api/utils;utilspbb\x06proto3"

var (
	file_proto_utils_proto_rawDescOnce sync.Once
	file_proto_utils_proto_rawDescData []byte
)

func file_proto_utils_proto_rawDescGZIP() []byte {
	file_proto_utils_proto_rawDescOnce.Do(func() {
		file_proto_utils_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_utils_proto_rawDesc), len(file_proto_utils_proto_rawDesc)))
	})
	return file_proto_utils_proto_rawDescData
}

var file_proto_utils_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_utils_proto_goTypes = []any{
	(*SendPacketRequest)(nil),                      // 0: fateark.proto.utils.SendPacketRequest
	(*SendBytePacketRequest)(nil),                  // 1: fateark.proto.utils.SendBytePacketRequest
	(*GetPacketNameIDMappingRequest)(nil),          // 2: fateark.proto.utils.GetPacketNameIDMappingRequest
	(*GetClientMaintainedBotBasicInfoRequest)(nil), // 3: fateark.proto.utils.GetClientMaintainedBotBasicInfoRequest
	(*GetClientMaintainedExtendInfoRequest)(nil),   // 4: fateark.proto.utils.GetClientMaintainedExtendInfoRequest
	(*response.GeneralResponse)(nil),               // 5: fateark.proto.response.GeneralResponse
}
var file_proto_utils_proto_depIdxs = []int32{
	0, // 0: fateark.proto.utils.UtilsService.SendPacket:input_type -> fateark.proto.utils.SendPacketRequest
	1, // 1: fateark.proto.utils.UtilsService.SendBytePacket:input_type -> fateark.proto.utils.SendBytePacketRequest
	2, // 2: fateark.proto.utils.UtilsService.GetPacketNameIDMapping:input_type -> fateark.proto.utils.GetPacketNameIDMappingRequest
	3, // 3: fateark.proto.utils.UtilsService.GetClientMaintainedBotBasicInfo:input_type -> fateark.proto.utils.GetClientMaintainedBotBasicInfoRequest
	4, // 4: fateark.proto.utils.UtilsService.GetClientMaintainedExtendInfo:input_type -> fateark.proto.utils.GetClientMaintainedExtendInfoRequest
	5, // 5: fateark.proto.utils.UtilsService.SendPacket:output_type -> fateark.proto.response.GeneralResponse
	5, // 6: fateark.proto.utils.UtilsService.SendBytePacket:output_type -> fateark.proto.response.GeneralResponse
	5, // 7: fateark.proto.utils.UtilsService.GetPacketNameIDMapping:output_type -> fateark.proto.response.GeneralResponse
	5, // 8: fateark.proto.utils.UtilsService.GetClientMaintainedBotBasicInfo:output_type -> fateark.proto.response.GeneralResponse
	5, // 9: fateark.proto.utils.UtilsService.GetClientMaintainedExtendInfo:output_type -> fateark.proto.response.GeneralResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_utils_proto_init() }
func file_proto_utils_proto_init() {
	if File_proto_utils_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_utils_proto_rawDesc), len(file_proto_utils_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_utils_proto_goTypes,
		DependencyIndexes: file_proto_utils_proto_depIdxs,
		MessageInfos:      file_proto_utils_proto_msgTypes,
	}.Build()
	File_proto_utils_proto = out.File
	file_proto_utils_proto_goTypes = nil
	file_proto_utils_proto_depIdxs = nil
}
