// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/response.proto

package responsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralResponse_Status int32

const (
	GeneralResponse_SUCCESS GeneralResponse_Status = 0
	GeneralResponse_FAILED  GeneralResponse_Status = 1
)

// Enum value maps for GeneralResponse_Status.
var (
	GeneralResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	GeneralResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x GeneralResponse_Status) Enum() *GeneralResponse_Status {
	p := new(GeneralResponse_Status)
	*p = x
	return p
}

func (x GeneralResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeneralResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_response_proto_enumTypes[0].Descriptor()
}

func (GeneralResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_response_proto_enumTypes[0]
}

func (x GeneralResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeneralResponse_Status.Descriptor instead.
func (GeneralResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{0, 0}
}

type GeneralInt32Response_Status int32

const (
	GeneralInt32Response_SUCCESS GeneralInt32Response_Status = 0
	GeneralInt32Response_FAILED  GeneralInt32Response_Status = 1
)

// Enum value maps for GeneralInt32Response_Status.
var (
	GeneralInt32Response_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	GeneralInt32Response_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x GeneralInt32Response_Status) Enum() *GeneralInt32Response_Status {
	p := new(GeneralInt32Response_Status)
	*p = x
	return p
}

func (x GeneralInt32Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeneralInt32Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_response_proto_enumTypes[1].Descriptor()
}

func (GeneralInt32Response_Status) Type() protoreflect.EnumType {
	return &file_proto_response_proto_enumTypes[1]
}

func (x GeneralInt32Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeneralInt32Response_Status.Descriptor instead.
func (GeneralInt32Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{1, 0}
}

type GeneralInt64Response_Status int32

const (
	GeneralInt64Response_SUCCESS GeneralInt64Response_Status = 0
	GeneralInt64Response_FAILED  GeneralInt64Response_Status = 1
)

// Enum value maps for GeneralInt64Response_Status.
var (
	GeneralInt64Response_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	GeneralInt64Response_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x GeneralInt64Response_Status) Enum() *GeneralInt64Response_Status {
	p := new(GeneralInt64Response_Status)
	*p = x
	return p
}

func (x GeneralInt64Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeneralInt64Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_response_proto_enumTypes[2].Descriptor()
}

func (GeneralInt64Response_Status) Type() protoreflect.EnumType {
	return &file_proto_response_proto_enumTypes[2]
}

func (x GeneralInt64Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeneralInt64Response_Status.Descriptor instead.
func (GeneralInt64Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{2, 0}
}

type GeneralUint64Response_Status int32

const (
	GeneralUint64Response_SUCCESS GeneralUint64Response_Status = 0
	GeneralUint64Response_FAILED  GeneralUint64Response_Status = 1
)

// Enum value maps for GeneralUint64Response_Status.
var (
	GeneralUint64Response_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	GeneralUint64Response_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x GeneralUint64Response_Status) Enum() *GeneralUint64Response_Status {
	p := new(GeneralUint64Response_Status)
	*p = x
	return p
}

func (x GeneralUint64Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeneralUint64Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_response_proto_enumTypes[3].Descriptor()
}

func (GeneralUint64Response_Status) Type() protoreflect.EnumType {
	return &file_proto_response_proto_enumTypes[3]
}

func (x GeneralUint64Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeneralUint64Response_Status.Descriptor instead.
func (GeneralUint64Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{3, 0}
}

type GeneralBoolResponse_Status int32

const (
	GeneralBoolResponse_SUCCESS GeneralBoolResponse_Status = 0
	GeneralBoolResponse_FAILED  GeneralBoolResponse_Status = 1
)

// Enum value maps for GeneralBoolResponse_Status.
var (
	GeneralBoolResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	GeneralBoolResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x GeneralBoolResponse_Status) Enum() *GeneralBoolResponse_Status {
	p := new(GeneralBoolResponse_Status)
	*p = x
	return p
}

func (x GeneralBoolResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeneralBoolResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_response_proto_enumTypes[4].Descriptor()
}

func (GeneralBoolResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_response_proto_enumTypes[4]
}

func (x GeneralBoolResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeneralBoolResponse_Status.Descriptor instead.
func (GeneralBoolResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{4, 0}
}

type GeneralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GeneralResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=fateark.proto.response.GeneralResponse_Status" json:"status,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralResponse) Reset() {
	*x = GeneralResponse{}
	mi := &file_proto_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResponse) ProtoMessage() {}

func (x *GeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResponse.ProtoReflect.Descriptor instead.
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralResponse) GetStatus() GeneralResponse_Status {
	if x != nil {
		return x.Status
	}
	return GeneralResponse_SUCCESS
}

func (x *GeneralResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GeneralResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GeneralInt32Response struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        GeneralInt32Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=fateark.proto.response.GeneralInt32Response_Status" json:"status,omitempty"`
	Payload       int32                       `protobuf:"varint,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorMsg      string                      `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralInt32Response) Reset() {
	*x = GeneralInt32Response{}
	mi := &file_proto_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralInt32Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralInt32Response) ProtoMessage() {}

func (x *GeneralInt32Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralInt32Response.ProtoReflect.Descriptor instead.
func (*GeneralInt32Response) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{1}
}

func (x *GeneralInt32Response) GetStatus() GeneralInt32Response_Status {
	if x != nil {
		return x.Status
	}
	return GeneralInt32Response_SUCCESS
}

func (x *GeneralInt32Response) GetPayload() int32 {
	if x != nil {
		return x.Payload
	}
	return 0
}

func (x *GeneralInt32Response) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GeneralInt64Response struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        GeneralInt64Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=fateark.proto.response.GeneralInt64Response_Status" json:"status,omitempty"`
	Payload       int64                       `protobuf:"varint,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorMsg      string                      `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralInt64Response) Reset() {
	*x = GeneralInt64Response{}
	mi := &file_proto_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralInt64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralInt64Response) ProtoMessage() {}

func (x *GeneralInt64Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralInt64Response.ProtoReflect.Descriptor instead.
func (*GeneralInt64Response) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{2}
}

func (x *GeneralInt64Response) GetStatus() GeneralInt64Response_Status {
	if x != nil {
		return x.Status
	}
	return GeneralInt64Response_SUCCESS
}

func (x *GeneralInt64Response) GetPayload() int64 {
	if x != nil {
		return x.Payload
	}
	return 0
}

func (x *GeneralInt64Response) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GeneralUint64Response struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        GeneralUint64Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=fateark.proto.response.GeneralUint64Response_Status" json:"status,omitempty"`
	Payload       uint64                       `protobuf:"varint,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorMsg      string                       `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralUint64Response) Reset() {
	*x = GeneralUint64Response{}
	mi := &file_proto_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralUint64Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralUint64Response) ProtoMessage() {}

func (x *GeneralUint64Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralUint64Response.ProtoReflect.Descriptor instead.
func (*GeneralUint64Response) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{3}
}

func (x *GeneralUint64Response) GetStatus() GeneralUint64Response_Status {
	if x != nil {
		return x.Status
	}
	return GeneralUint64Response_SUCCESS
}

func (x *GeneralUint64Response) GetPayload() uint64 {
	if x != nil {
		return x.Payload
	}
	return 0
}

func (x *GeneralUint64Response) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GeneralBoolResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        GeneralBoolResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=fateark.proto.response.GeneralBoolResponse_Status" json:"status,omitempty"`
	Payload       bool                       `protobuf:"varint,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorMsg      string                     `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralBoolResponse) Reset() {
	*x = GeneralBoolResponse{}
	mi := &file_proto_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralBoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralBoolResponse) ProtoMessage() {}

func (x *GeneralBoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralBoolResponse.ProtoReflect.Descriptor instead.
func (*GeneralBoolResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{4}
}

func (x *GeneralBoolResponse) GetStatus() GeneralBoolResponse_Status {
	if x != nil {
		return x.Status
	}
	return GeneralBoolResponse_SUCCESS
}

func (x *GeneralBoolResponse) GetPayload() bool {
	if x != nil {
		return x.Payload
	}
	return false
}

func (x *GeneralBoolResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type DeadReason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadReason) Reset() {
	*x = DeadReason{}
	mi := &file_proto_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadReason) ProtoMessage() {}

func (x *DeadReason) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadReason.ProtoReflect.Descriptor instead.
func (*DeadReason) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{5}
}

func (x *DeadReason) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_response_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_response_proto protoreflect.FileDescriptor

const file_proto_response_proto_rawDesc = "" +
	"\n" +
	"\x14proto/response.proto\x12\x16fateark.proto.response\"\xb3\x01\n" +
	"\x0fGeneralResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..fateark.proto.response.GeneralResponse.StatusR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"!\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"\xbd\x01\n" +
	"\x14GeneralInt32Response\x12K\n" +
	"\x06status\x18\x01 \x01(\x0e23.fateark.proto.response.GeneralInt32Response.StatusR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\x05R\apayload\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"!\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"\xbd\x01\n" +
	"\x14GeneralInt64Response\x12K\n" +
	"\x06status\x18\x01 \x01(\x0e23.fateark.proto.response.GeneralInt64Response.StatusR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\x03R\apayload\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"!\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"\xbf\x01\n" +
	"\x15GeneralUint64Response\x12L\n" +
	"\x06status\x18\x01 \x01(\x0e24.fateark.proto.response.GeneralUint64Response.StatusR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\x04R\apayload\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"!\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"\xbb\x01\n" +
	"\x13GeneralBoolResponse\x12J\n" +
	"\x06status\x18\x01 \x01(\x0e22.fateark.proto.response.GeneralBoolResponse.StatusR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\bR\apayload\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\"!\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\"$\n" +
	"\n" +
	"DeadReason\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessBAZ?github.com/Yeah114/tempest-core/network_api/response;responsepbb\x06proto3"

var (
	file_proto_response_proto_rawDescOnce sync.Once
	file_proto_response_proto_rawDescData []byte
)

func file_proto_response_proto_rawDescGZIP() []byte {
	file_proto_response_proto_rawDescOnce.Do(func() {
		file_proto_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_response_proto_rawDesc), len(file_proto_response_proto_rawDesc)))
	})
	return file_proto_response_proto_rawDescData
}

var file_proto_response_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_response_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_response_proto_goTypes = []any{
	(GeneralResponse_Status)(0),       // 0: fateark.proto.response.GeneralResponse.Status
	(GeneralInt32Response_Status)(0),  // 1: fateark.proto.response.GeneralInt32Response.Status
	(GeneralInt64Response_Status)(0),  // 2: fateark.proto.response.GeneralInt64Response.Status
	(GeneralUint64Response_Status)(0), // 3: fateark.proto.response.GeneralUint64Response.Status
	(GeneralBoolResponse_Status)(0),   // 4: fateark.proto.response.GeneralBoolResponse.Status
	(*GeneralResponse)(nil),           // 5: fateark.proto.response.GeneralResponse
	(*GeneralInt32Response)(nil),      // 6: fateark.proto.response.GeneralInt32Response
	(*GeneralInt64Response)(nil),      // 7: fateark.proto.response.GeneralInt64Response
	(*GeneralUint64Response)(nil),     // 8: fateark.proto.response.GeneralUint64Response
	(*GeneralBoolResponse)(nil),       // 9: fateark.proto.response.GeneralBoolResponse
	(*DeadReason)(nil),                // 10: fateark.proto.response.DeadReason
	(*PingResponse)(nil),              // 11: fateark.proto.response.PingResponse
}
var file_proto_response_proto_depIdxs = []int32{
	0, // 0: fateark.proto.response.GeneralResponse.status:type_name -> fateark.proto.response.GeneralResponse.Status
	1, // 1: fateark.proto.response.GeneralInt32Response.status:type_name -> fateark.proto.response.GeneralInt32Response.Status
	2, // 2: fateark.proto.response.GeneralInt64Response.status:type_name -> fateark.proto.response.GeneralInt64Response.Status
	3, // 3: fateark.proto.response.GeneralUint64Response.status:type_name -> fateark.proto.response.GeneralUint64Response.Status
	4, // 4: fateark.proto.response.GeneralBoolResponse.status:type_name -> fateark.proto.response.GeneralBoolResponse.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_response_proto_init() }
func file_proto_response_proto_init() {
	if File_proto_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_response_proto_rawDesc), len(file_proto_response_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_response_proto_goTypes,
		DependencyIndexes: file_proto_response_proto_depIdxs,
		EnumInfos:         file_proto_response_proto_enumTypes,
		MessageInfos:      file_proto_response_proto_msgTypes,
	}.Build()
	File_proto_response_proto = out.File
	file_proto_response_proto_goTypes = nil
	file_proto_response_proto_depIdxs = nil
}
