// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/playerkit.proto

package playerkitpb

import (
	response "github.com/Yeah114/tempest-core/network_api/response"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllOnlinePlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOnlinePlayersRequest) Reset() {
	*x = GetAllOnlinePlayersRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOnlinePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOnlinePlayersRequest) ProtoMessage() {}

func (x *GetAllOnlinePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOnlinePlayersRequest.ProtoReflect.Descriptor instead.
func (*GetAllOnlinePlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{0}
}

type GetPlayerByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByNameRequest) Reset() {
	*x = GetPlayerByNameRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByNameRequest) ProtoMessage() {}

func (x *GetPlayerByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByNameRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPlayerByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerByUUIDRequest) Reset() {
	*x = GetPlayerByUUIDRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerByUUIDRequest) ProtoMessage() {}

func (x *GetPlayerByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ReleaseBindPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseBindPlayerRequest) Reset() {
	*x = ReleaseBindPlayerRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseBindPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseBindPlayerRequest) ProtoMessage() {}

func (x *ReleaseBindPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseBindPlayerRequest.ProtoReflect.Descriptor instead.
func (*ReleaseBindPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseBindPlayerRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerNameRequest) Reset() {
	*x = GetPlayerNameRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerNameRequest) ProtoMessage() {}

func (x *GetPlayerNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerNameRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerNameRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerEntityUniqueIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerEntityUniqueIDRequest) Reset() {
	*x = GetPlayerEntityUniqueIDRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerEntityUniqueIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerEntityUniqueIDRequest) ProtoMessage() {}

func (x *GetPlayerEntityUniqueIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerEntityUniqueIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerEntityUniqueIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlayerEntityUniqueIDRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerLoginTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerLoginTimeRequest) Reset() {
	*x = GetPlayerLoginTimeRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerLoginTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerLoginTimeRequest) ProtoMessage() {}

func (x *GetPlayerLoginTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerLoginTimeRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerLoginTimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlayerLoginTimeRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerPlatformChatIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerPlatformChatIDRequest) Reset() {
	*x = GetPlayerPlatformChatIDRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerPlatformChatIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerPlatformChatIDRequest) ProtoMessage() {}

func (x *GetPlayerPlatformChatIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerPlatformChatIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerPlatformChatIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlayerPlatformChatIDRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerBuildPlatformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerBuildPlatformRequest) Reset() {
	*x = GetPlayerBuildPlatformRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerBuildPlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerBuildPlatformRequest) ProtoMessage() {}

func (x *GetPlayerBuildPlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerBuildPlatformRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerBuildPlatformRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlayerBuildPlatformRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerSkinIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerSkinIDRequest) Reset() {
	*x = GetPlayerSkinIDRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerSkinIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerSkinIDRequest) ProtoMessage() {}

func (x *GetPlayerSkinIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerSkinIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerSkinIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{9}
}

func (x *GetPlayerSkinIDRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerCanBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanBuildRequest) Reset() {
	*x = GetPlayerCanBuildRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanBuildRequest) ProtoMessage() {}

func (x *GetPlayerCanBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanBuildRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanBuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlayerCanBuildRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanBuildRequest) Reset() {
	*x = SetPlayerCanBuildRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanBuildRequest) ProtoMessage() {}

func (x *SetPlayerCanBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanBuildRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanBuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{11}
}

func (x *SetPlayerCanBuildRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanBuildRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerCanDigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanDigRequest) Reset() {
	*x = GetPlayerCanDigRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanDigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanDigRequest) ProtoMessage() {}

func (x *GetPlayerCanDigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanDigRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanDigRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{12}
}

func (x *GetPlayerCanDigRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanDigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanDigRequest) Reset() {
	*x = SetPlayerCanDigRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanDigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanDigRequest) ProtoMessage() {}

func (x *SetPlayerCanDigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanDigRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanDigRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{13}
}

func (x *SetPlayerCanDigRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanDigRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerCanDoorsAndSwitchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanDoorsAndSwitchesRequest) Reset() {
	*x = GetPlayerCanDoorsAndSwitchesRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanDoorsAndSwitchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanDoorsAndSwitchesRequest) ProtoMessage() {}

func (x *GetPlayerCanDoorsAndSwitchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanDoorsAndSwitchesRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanDoorsAndSwitchesRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{14}
}

func (x *GetPlayerCanDoorsAndSwitchesRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanDoorsAndSwitchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanDoorsAndSwitchesRequest) Reset() {
	*x = SetPlayerCanDoorsAndSwitchesRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanDoorsAndSwitchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanDoorsAndSwitchesRequest) ProtoMessage() {}

func (x *SetPlayerCanDoorsAndSwitchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanDoorsAndSwitchesRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanDoorsAndSwitchesRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{15}
}

func (x *SetPlayerCanDoorsAndSwitchesRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanDoorsAndSwitchesRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerCanOpenContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanOpenContainersRequest) Reset() {
	*x = GetPlayerCanOpenContainersRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanOpenContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanOpenContainersRequest) ProtoMessage() {}

func (x *GetPlayerCanOpenContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanOpenContainersRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanOpenContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{16}
}

func (x *GetPlayerCanOpenContainersRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanOpenContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanOpenContainersRequest) Reset() {
	*x = SetPlayerCanOpenContainersRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanOpenContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanOpenContainersRequest) ProtoMessage() {}

func (x *SetPlayerCanOpenContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanOpenContainersRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanOpenContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{17}
}

func (x *SetPlayerCanOpenContainersRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanOpenContainersRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerCanAttackPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanAttackPlayersRequest) Reset() {
	*x = GetPlayerCanAttackPlayersRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanAttackPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanAttackPlayersRequest) ProtoMessage() {}

func (x *GetPlayerCanAttackPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanAttackPlayersRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanAttackPlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlayerCanAttackPlayersRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanAttackPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanAttackPlayersRequest) Reset() {
	*x = SetPlayerCanAttackPlayersRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanAttackPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanAttackPlayersRequest) ProtoMessage() {}

func (x *SetPlayerCanAttackPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanAttackPlayersRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanAttackPlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{19}
}

func (x *SetPlayerCanAttackPlayersRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanAttackPlayersRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerCanAttackMobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanAttackMobsRequest) Reset() {
	*x = GetPlayerCanAttackMobsRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanAttackMobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanAttackMobsRequest) ProtoMessage() {}

func (x *GetPlayerCanAttackMobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanAttackMobsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanAttackMobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{20}
}

func (x *GetPlayerCanAttackMobsRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanAttackMobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanAttackMobsRequest) Reset() {
	*x = SetPlayerCanAttackMobsRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanAttackMobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanAttackMobsRequest) ProtoMessage() {}

func (x *SetPlayerCanAttackMobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanAttackMobsRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanAttackMobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{21}
}

func (x *SetPlayerCanAttackMobsRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanAttackMobsRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerCanOperatorCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanOperatorCommandsRequest) Reset() {
	*x = GetPlayerCanOperatorCommandsRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanOperatorCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanOperatorCommandsRequest) ProtoMessage() {}

func (x *GetPlayerCanOperatorCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanOperatorCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanOperatorCommandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{22}
}

func (x *GetPlayerCanOperatorCommandsRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanOperatorCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanOperatorCommandsRequest) Reset() {
	*x = SetPlayerCanOperatorCommandsRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanOperatorCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanOperatorCommandsRequest) ProtoMessage() {}

func (x *SetPlayerCanOperatorCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanOperatorCommandsRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanOperatorCommandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{23}
}

func (x *SetPlayerCanOperatorCommandsRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanOperatorCommandsRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerCanTeleportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerCanTeleportRequest) Reset() {
	*x = GetPlayerCanTeleportRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerCanTeleportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerCanTeleportRequest) ProtoMessage() {}

func (x *GetPlayerCanTeleportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerCanTeleportRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerCanTeleportRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{24}
}

func (x *GetPlayerCanTeleportRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SetPlayerCanTeleportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlayerCanTeleportRequest) Reset() {
	*x = SetPlayerCanTeleportRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlayerCanTeleportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerCanTeleportRequest) ProtoMessage() {}

func (x *SetPlayerCanTeleportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerCanTeleportRequest.ProtoReflect.Descriptor instead.
func (*SetPlayerCanTeleportRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{25}
}

func (x *SetPlayerCanTeleportRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SetPlayerCanTeleportRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type GetPlayerStatusInvulnerableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatusInvulnerableRequest) Reset() {
	*x = GetPlayerStatusInvulnerableRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatusInvulnerableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatusInvulnerableRequest) ProtoMessage() {}

func (x *GetPlayerStatusInvulnerableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatusInvulnerableRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerStatusInvulnerableRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{26}
}

func (x *GetPlayerStatusInvulnerableRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerStatusFlyingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatusFlyingRequest) Reset() {
	*x = GetPlayerStatusFlyingRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatusFlyingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatusFlyingRequest) ProtoMessage() {}

func (x *GetPlayerStatusFlyingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatusFlyingRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerStatusFlyingRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{27}
}

func (x *GetPlayerStatusFlyingRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerStatusMayFlyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatusMayFlyRequest) Reset() {
	*x = GetPlayerStatusMayFlyRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatusMayFlyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatusMayFlyRequest) ProtoMessage() {}

func (x *GetPlayerStatusMayFlyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatusMayFlyRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerStatusMayFlyRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{28}
}

func (x *GetPlayerStatusMayFlyRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerDeviceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerDeviceIDRequest) Reset() {
	*x = GetPlayerDeviceIDRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerDeviceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerDeviceIDRequest) ProtoMessage() {}

func (x *GetPlayerDeviceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerDeviceIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerDeviceIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{29}
}

func (x *GetPlayerDeviceIDRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerEntityRuntimeIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerEntityRuntimeIDRequest) Reset() {
	*x = GetPlayerEntityRuntimeIDRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerEntityRuntimeIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerEntityRuntimeIDRequest) ProtoMessage() {}

func (x *GetPlayerEntityRuntimeIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerEntityRuntimeIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerEntityRuntimeIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{30}
}

func (x *GetPlayerEntityRuntimeIDRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerEntityMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerEntityMetadataRequest) Reset() {
	*x = GetPlayerEntityMetadataRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerEntityMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerEntityMetadataRequest) ProtoMessage() {}

func (x *GetPlayerEntityMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerEntityMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerEntityMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{31}
}

func (x *GetPlayerEntityMetadataRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerIsOPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerIsOPRequest) Reset() {
	*x = GetPlayerIsOPRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerIsOPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerIsOPRequest) ProtoMessage() {}

func (x *GetPlayerIsOPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerIsOPRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerIsOPRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{32}
}

func (x *GetPlayerIsOPRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type GetPlayerOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerOnlineRequest) Reset() {
	*x = GetPlayerOnlineRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerOnlineRequest) ProtoMessage() {}

func (x *GetPlayerOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerOnlineRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerOnlineRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{33}
}

func (x *GetPlayerOnlineRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

type SendPlayerChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerChatRequest) Reset() {
	*x = SendPlayerChatRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerChatRequest) ProtoMessage() {}

func (x *SendPlayerChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerChatRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{34}
}

func (x *SendPlayerChatRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SendPlayerChatRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendPlayerRawChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerRawChatRequest) Reset() {
	*x = SendPlayerRawChatRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerRawChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerRawChatRequest) ProtoMessage() {}

func (x *SendPlayerRawChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerRawChatRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerRawChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{35}
}

func (x *SendPlayerRawChatRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SendPlayerRawChatRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendPlayerTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle      string                 `protobuf:"bytes,3,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerTitleRequest) Reset() {
	*x = SendPlayerTitleRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerTitleRequest) ProtoMessage() {}

func (x *SendPlayerTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerTitleRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerTitleRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{36}
}

func (x *SendPlayerTitleRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SendPlayerTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendPlayerTitleRequest) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

type SendPlayerActionBarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	ActionBar     string                 `protobuf:"bytes,2,opt,name=action_bar,json=actionBar,proto3" json:"action_bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayerActionBarRequest) Reset() {
	*x = SendPlayerActionBarRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayerActionBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayerActionBarRequest) ProtoMessage() {}

func (x *SendPlayerActionBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayerActionBarRequest.ProtoReflect.Descriptor instead.
func (*SendPlayerActionBarRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{37}
}

func (x *SendPlayerActionBarRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *SendPlayerActionBarRequest) GetActionBar() string {
	if x != nil {
		return x.ActionBar
	}
	return ""
}

type InterceptPlayerJustNextInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UuidStr       string                 `protobuf:"bytes,1,opt,name=uuid_str,json=uuidStr,proto3" json:"uuid_str,omitempty"`
	RetrieverId   string                 `protobuf:"bytes,2,opt,name=retriever_id,json=retrieverId,proto3" json:"retriever_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptPlayerJustNextInputRequest) Reset() {
	*x = InterceptPlayerJustNextInputRequest{}
	mi := &file_proto_playerkit_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptPlayerJustNextInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptPlayerJustNextInputRequest) ProtoMessage() {}

func (x *InterceptPlayerJustNextInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_playerkit_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptPlayerJustNextInputRequest.ProtoReflect.Descriptor instead.
func (*InterceptPlayerJustNextInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_playerkit_proto_rawDescGZIP(), []int{38}
}

func (x *InterceptPlayerJustNextInputRequest) GetUuidStr() string {
	if x != nil {
		return x.UuidStr
	}
	return ""
}

func (x *InterceptPlayerJustNextInputRequest) GetRetrieverId() string {
	if x != nil {
		return x.RetrieverId
	}
	return ""
}

var File_proto_playerkit_proto protoreflect.FileDescriptor

const file_proto_playerkit_proto_rawDesc = "" +
	"\n" +
	"\x15proto/playerkit.proto\x12\x17fateark.proto.playerkit\x1a\x14proto/response.proto\"\x1c\n" +
	"\x1aGetAllOnlinePlayersRequest\",\n" +
	"\x16GetPlayerByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16GetPlayerByUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"5\n" +
	"\x18ReleaseBindPlayerRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"1\n" +
	"\x14GetPlayerNameRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\";\n" +
	"\x1eGetPlayerEntityUniqueIDRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"6\n" +
	"\x19GetPlayerLoginTimeRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\";\n" +
	"\x1eGetPlayerPlatformChatIDRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\":\n" +
	"\x1dGetPlayerBuildPlatformRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"3\n" +
	"\x16GetPlayerSkinIDRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"5\n" +
	"\x18GetPlayerCanBuildRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"K\n" +
	"\x18SetPlayerCanBuildRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"3\n" +
	"\x16GetPlayerCanDigRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"I\n" +
	"\x16SetPlayerCanDigRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"@\n" +
	"#GetPlayerCanDoorsAndSwitchesRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"V\n" +
	"#SetPlayerCanDoorsAndSwitchesRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\">\n" +
	"!GetPlayerCanOpenContainersRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"T\n" +
	"!SetPlayerCanOpenContainersRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"=\n" +
	" GetPlayerCanAttackPlayersRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"S\n" +
	" SetPlayerCanAttackPlayersRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\":\n" +
	"\x1dGetPlayerCanAttackMobsRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"P\n" +
	"\x1dSetPlayerCanAttackMobsRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"@\n" +
	"#GetPlayerCanOperatorCommandsRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"V\n" +
	"#SetPlayerCanOperatorCommandsRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"8\n" +
	"\x1bGetPlayerCanTeleportRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"N\n" +
	"\x1bSetPlayerCanTeleportRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"?\n" +
	"\"GetPlayerStatusInvulnerableRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"9\n" +
	"\x1cGetPlayerStatusFlyingRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"9\n" +
	"\x1cGetPlayerStatusMayFlyRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"5\n" +
	"\x18GetPlayerDeviceIDRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"<\n" +
	"\x1fGetPlayerEntityRuntimeIDRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\";\n" +
	"\x1eGetPlayerEntityMetadataRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"1\n" +
	"\x14GetPlayerIsOPRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"3\n" +
	"\x16GetPlayerOnlineRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\"D\n" +
	"\x15SendPlayerChatRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"G\n" +
	"\x18SendPlayerRawChatRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"f\n" +
	"\x16SendPlayerTitleRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tsub_title\x18\x03 \x01(\tR\bsubTitle\"V\n" +
	"\x1aSendPlayerActionBarRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12\x1d\n" +
	"\n" +
	"action_bar\x18\x02 \x01(\tR\tactionBar\"c\n" +
	"#InterceptPlayerJustNextInputRequest\x12\x19\n" +
	"\buuid_str\x18\x01 \x01(\tR\auuidStr\x12!\n" +
	"\fretriever_id\x18\x02 \x01(\tR\vretrieverId2\xab%\n" +
	"\x10PlayerKitService\x12s\n" +
	"\x13GetAllOnlinePlayers\x123.fateark.proto.playerkit.GetAllOnlinePlayersRequest\x1a'.fateark.proto.response.GeneralResponse\x12k\n" +
	"\x0fGetPlayerByName\x12/.fateark.proto.playerkit.GetPlayerByNameRequest\x1a'.fateark.proto.response.GeneralResponse\x12k\n" +
	"\x0fGetPlayerByUUID\x12/.fateark.proto.playerkit.GetPlayerByUUIDRequest\x1a'.fateark.proto.response.GeneralResponse\x12o\n" +
	"\x11ReleaseBindPlayer\x121.fateark.proto.playerkit.ReleaseBindPlayerRequest\x1a'.fateark.proto.response.GeneralResponse\x12g\n" +
	"\rGetPlayerName\x12-.fateark.proto.playerkit.GetPlayerNameRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x80\x01\n" +
	"\x17GetPlayerEntityUniqueID\x127.fateark.proto.playerkit.GetPlayerEntityUniqueIDRequest\x1a,.fateark.proto.response.GeneralInt64Response\x12v\n" +
	"\x12GetPlayerLoginTime\x122.fateark.proto.playerkit.GetPlayerLoginTimeRequest\x1a,.fateark.proto.response.GeneralInt64Response\x12{\n" +
	"\x17GetPlayerPlatformChatID\x127.fateark.proto.playerkit.GetPlayerPlatformChatIDRequest\x1a'.fateark.proto.response.GeneralResponse\x12~\n" +
	"\x16GetPlayerBuildPlatform\x126.fateark.proto.playerkit.GetPlayerBuildPlatformRequest\x1a,.fateark.proto.response.GeneralInt32Response\x12k\n" +
	"\x0fGetPlayerSkinID\x12/.fateark.proto.playerkit.GetPlayerSkinIDRequest\x1a'.fateark.proto.response.GeneralResponse\x12s\n" +
	"\x11GetPlayerCanBuild\x121.fateark.proto.playerkit.GetPlayerCanBuildRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12o\n" +
	"\x11SetPlayerCanBuild\x121.fateark.proto.playerkit.SetPlayerCanBuildRequest\x1a'.fateark.proto.response.GeneralResponse\x12o\n" +
	"\x0fGetPlayerCanDig\x12/.fateark.proto.playerkit.GetPlayerCanDigRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12k\n" +
	"\x0fSetPlayerCanDig\x12/.fateark.proto.playerkit.SetPlayerCanDigRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x89\x01\n" +
	"\x1cGetPlayerCanDoorsAndSwitches\x12<.fateark.proto.playerkit.GetPlayerCanDoorsAndSwitchesRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12\x85\x01\n" +
	"\x1cSetPlayerCanDoorsAndSwitches\x12<.fateark.proto.playerkit.SetPlayerCanDoorsAndSwitchesRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x85\x01\n" +
	"\x1aGetPlayerCanOpenContainers\x12:.fateark.proto.playerkit.GetPlayerCanOpenContainersRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12\x81\x01\n" +
	"\x1aSetPlayerCanOpenContainers\x12:.fateark.proto.playerkit.SetPlayerCanOpenContainersRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x83\x01\n" +
	"\x19GetPlayerCanAttackPlayers\x129.fateark.proto.playerkit.GetPlayerCanAttackPlayersRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12\x7f\n" +
	"\x19SetPlayerCanAttackPlayers\x129.fateark.proto.playerkit.SetPlayerCanAttackPlayersRequest\x1a'.fateark.proto.response.GeneralResponse\x12}\n" +
	"\x16GetPlayerCanAttackMobs\x126.fateark.proto.playerkit.GetPlayerCanAttackMobsRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12y\n" +
	"\x16SetPlayerCanAttackMobs\x126.fateark.proto.playerkit.SetPlayerCanAttackMobsRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x89\x01\n" +
	"\x1cGetPlayerCanOperatorCommands\x12<.fateark.proto.playerkit.GetPlayerCanOperatorCommandsRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12\x85\x01\n" +
	"\x1cSetPlayerCanOperatorCommands\x12<.fateark.proto.playerkit.SetPlayerCanOperatorCommandsRequest\x1a'.fateark.proto.response.GeneralResponse\x12y\n" +
	"\x14GetPlayerCanTeleport\x124.fateark.proto.playerkit.GetPlayerCanTeleportRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12y\n" +
	"\x14SetPlayerCanTeleport\x124.fateark.proto.playerkit.SetPlayerCanTeleportRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12\x87\x01\n" +
	"\x1bGetPlayerStatusInvulnerable\x12;.fateark.proto.playerkit.GetPlayerStatusInvulnerableRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12{\n" +
	"\x15GetPlayerStatusFlying\x125.fateark.proto.playerkit.GetPlayerStatusFlyingRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12{\n" +
	"\x15GetPlayerStatusMayFly\x125.fateark.proto.playerkit.GetPlayerStatusMayFlyRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12o\n" +
	"\x11GetPlayerDeviceID\x121.fateark.proto.playerkit.GetPlayerDeviceIDRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x83\x01\n" +
	"\x18GetPlayerEntityRuntimeID\x128.fateark.proto.playerkit.GetPlayerEntityRuntimeIDRequest\x1a-.fateark.proto.response.GeneralUint64Response\x12{\n" +
	"\x17GetPlayerEntityMetadata\x127.fateark.proto.playerkit.GetPlayerEntityMetadataRequest\x1a'.fateark.proto.response.GeneralResponse\x12k\n" +
	"\rGetPlayerIsOP\x12-.fateark.proto.playerkit.GetPlayerIsOPRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12o\n" +
	"\x0fGetPlayerOnline\x12/.fateark.proto.playerkit.GetPlayerOnlineRequest\x1a+.fateark.proto.response.GeneralBoolResponse\x12i\n" +
	"\x0eSendPlayerChat\x12..fateark.proto.playerkit.SendPlayerChatRequest\x1a'.fateark.proto.response.GeneralResponse\x12o\n" +
	"\x11SendPlayerRawChat\x121.fateark.proto.playerkit.SendPlayerRawChatRequest\x1a'.fateark.proto.response.GeneralResponse\x12k\n" +
	"\x0fSendPlayerTitle\x12/.fateark.proto.playerkit.SendPlayerTitleRequest\x1a'.fateark.proto.response.GeneralResponse\x12s\n" +
	"\x13SendPlayerActionBar\x123.fateark.proto.playerkit.SendPlayerActionBarRequest\x1a'.fateark.proto.response.GeneralResponse\x12\x85\x01\n" +
	"\x1cInterceptPlayerJustNextInput\x12<.fateark.proto.playerkit.InterceptPlayerJustNextInputRequest\x1a'.fateark.proto.response.GeneralResponseBCZAgithub.com/Yeah114/tempest-core/network_api/playerkit;playerkitpbb\x06proto3"

var (
	file_proto_playerkit_proto_rawDescOnce sync.Once
	file_proto_playerkit_proto_rawDescData []byte
)

func file_proto_playerkit_proto_rawDescGZIP() []byte {
	file_proto_playerkit_proto_rawDescOnce.Do(func() {
		file_proto_playerkit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_playerkit_proto_rawDesc), len(file_proto_playerkit_proto_rawDesc)))
	})
	return file_proto_playerkit_proto_rawDescData
}

var file_proto_playerkit_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_proto_playerkit_proto_goTypes = []any{
	(*GetAllOnlinePlayersRequest)(nil),          // 0: fateark.proto.playerkit.GetAllOnlinePlayersRequest
	(*GetPlayerByNameRequest)(nil),              // 1: fateark.proto.playerkit.GetPlayerByNameRequest
	(*GetPlayerByUUIDRequest)(nil),              // 2: fateark.proto.playerkit.GetPlayerByUUIDRequest
	(*ReleaseBindPlayerRequest)(nil),            // 3: fateark.proto.playerkit.ReleaseBindPlayerRequest
	(*GetPlayerNameRequest)(nil),                // 4: fateark.proto.playerkit.GetPlayerNameRequest
	(*GetPlayerEntityUniqueIDRequest)(nil),      // 5: fateark.proto.playerkit.GetPlayerEntityUniqueIDRequest
	(*GetPlayerLoginTimeRequest)(nil),           // 6: fateark.proto.playerkit.GetPlayerLoginTimeRequest
	(*GetPlayerPlatformChatIDRequest)(nil),      // 7: fateark.proto.playerkit.GetPlayerPlatformChatIDRequest
	(*GetPlayerBuildPlatformRequest)(nil),       // 8: fateark.proto.playerkit.GetPlayerBuildPlatformRequest
	(*GetPlayerSkinIDRequest)(nil),              // 9: fateark.proto.playerkit.GetPlayerSkinIDRequest
	(*GetPlayerCanBuildRequest)(nil),            // 10: fateark.proto.playerkit.GetPlayerCanBuildRequest
	(*SetPlayerCanBuildRequest)(nil),            // 11: fateark.proto.playerkit.SetPlayerCanBuildRequest
	(*GetPlayerCanDigRequest)(nil),              // 12: fateark.proto.playerkit.GetPlayerCanDigRequest
	(*SetPlayerCanDigRequest)(nil),              // 13: fateark.proto.playerkit.SetPlayerCanDigRequest
	(*GetPlayerCanDoorsAndSwitchesRequest)(nil), // 14: fateark.proto.playerkit.GetPlayerCanDoorsAndSwitchesRequest
	(*SetPlayerCanDoorsAndSwitchesRequest)(nil), // 15: fateark.proto.playerkit.SetPlayerCanDoorsAndSwitchesRequest
	(*GetPlayerCanOpenContainersRequest)(nil),   // 16: fateark.proto.playerkit.GetPlayerCanOpenContainersRequest
	(*SetPlayerCanOpenContainersRequest)(nil),   // 17: fateark.proto.playerkit.SetPlayerCanOpenContainersRequest
	(*GetPlayerCanAttackPlayersRequest)(nil),    // 18: fateark.proto.playerkit.GetPlayerCanAttackPlayersRequest
	(*SetPlayerCanAttackPlayersRequest)(nil),    // 19: fateark.proto.playerkit.SetPlayerCanAttackPlayersRequest
	(*GetPlayerCanAttackMobsRequest)(nil),       // 20: fateark.proto.playerkit.GetPlayerCanAttackMobsRequest
	(*SetPlayerCanAttackMobsRequest)(nil),       // 21: fateark.proto.playerkit.SetPlayerCanAttackMobsRequest
	(*GetPlayerCanOperatorCommandsRequest)(nil), // 22: fateark.proto.playerkit.GetPlayerCanOperatorCommandsRequest
	(*SetPlayerCanOperatorCommandsRequest)(nil), // 23: fateark.proto.playerkit.SetPlayerCanOperatorCommandsRequest
	(*GetPlayerCanTeleportRequest)(nil),         // 24: fateark.proto.playerkit.GetPlayerCanTeleportRequest
	(*SetPlayerCanTeleportRequest)(nil),         // 25: fateark.proto.playerkit.SetPlayerCanTeleportRequest
	(*GetPlayerStatusInvulnerableRequest)(nil),  // 26: fateark.proto.playerkit.GetPlayerStatusInvulnerableRequest
	(*GetPlayerStatusFlyingRequest)(nil),        // 27: fateark.proto.playerkit.GetPlayerStatusFlyingRequest
	(*GetPlayerStatusMayFlyRequest)(nil),        // 28: fateark.proto.playerkit.GetPlayerStatusMayFlyRequest
	(*GetPlayerDeviceIDRequest)(nil),            // 29: fateark.proto.playerkit.GetPlayerDeviceIDRequest
	(*GetPlayerEntityRuntimeIDRequest)(nil),     // 30: fateark.proto.playerkit.GetPlayerEntityRuntimeIDRequest
	(*GetPlayerEntityMetadataRequest)(nil),      // 31: fateark.proto.playerkit.GetPlayerEntityMetadataRequest
	(*GetPlayerIsOPRequest)(nil),                // 32: fateark.proto.playerkit.GetPlayerIsOPRequest
	(*GetPlayerOnlineRequest)(nil),              // 33: fateark.proto.playerkit.GetPlayerOnlineRequest
	(*SendPlayerChatRequest)(nil),               // 34: fateark.proto.playerkit.SendPlayerChatRequest
	(*SendPlayerRawChatRequest)(nil),            // 35: fateark.proto.playerkit.SendPlayerRawChatRequest
	(*SendPlayerTitleRequest)(nil),              // 36: fateark.proto.playerkit.SendPlayerTitleRequest
	(*SendPlayerActionBarRequest)(nil),          // 37: fateark.proto.playerkit.SendPlayerActionBarRequest
	(*InterceptPlayerJustNextInputRequest)(nil), // 38: fateark.proto.playerkit.InterceptPlayerJustNextInputRequest
	(*response.GeneralResponse)(nil),            // 39: fateark.proto.response.GeneralResponse
	(*response.GeneralInt64Response)(nil),       // 40: fateark.proto.response.GeneralInt64Response
	(*response.GeneralInt32Response)(nil),       // 41: fateark.proto.response.GeneralInt32Response
	(*response.GeneralBoolResponse)(nil),        // 42: fateark.proto.response.GeneralBoolResponse
	(*response.GeneralUint64Response)(nil),      // 43: fateark.proto.response.GeneralUint64Response
}
var file_proto_playerkit_proto_depIdxs = []int32{
	0,  // 0: fateark.proto.playerkit.PlayerKitService.GetAllOnlinePlayers:input_type -> fateark.proto.playerkit.GetAllOnlinePlayersRequest
	1,  // 1: fateark.proto.playerkit.PlayerKitService.GetPlayerByName:input_type -> fateark.proto.playerkit.GetPlayerByNameRequest
	2,  // 2: fateark.proto.playerkit.PlayerKitService.GetPlayerByUUID:input_type -> fateark.proto.playerkit.GetPlayerByUUIDRequest
	3,  // 3: fateark.proto.playerkit.PlayerKitService.ReleaseBindPlayer:input_type -> fateark.proto.playerkit.ReleaseBindPlayerRequest
	4,  // 4: fateark.proto.playerkit.PlayerKitService.GetPlayerName:input_type -> fateark.proto.playerkit.GetPlayerNameRequest
	5,  // 5: fateark.proto.playerkit.PlayerKitService.GetPlayerEntityUniqueID:input_type -> fateark.proto.playerkit.GetPlayerEntityUniqueIDRequest
	6,  // 6: fateark.proto.playerkit.PlayerKitService.GetPlayerLoginTime:input_type -> fateark.proto.playerkit.GetPlayerLoginTimeRequest
	7,  // 7: fateark.proto.playerkit.PlayerKitService.GetPlayerPlatformChatID:input_type -> fateark.proto.playerkit.GetPlayerPlatformChatIDRequest
	8,  // 8: fateark.proto.playerkit.PlayerKitService.GetPlayerBuildPlatform:input_type -> fateark.proto.playerkit.GetPlayerBuildPlatformRequest
	9,  // 9: fateark.proto.playerkit.PlayerKitService.GetPlayerSkinID:input_type -> fateark.proto.playerkit.GetPlayerSkinIDRequest
	10, // 10: fateark.proto.playerkit.PlayerKitService.GetPlayerCanBuild:input_type -> fateark.proto.playerkit.GetPlayerCanBuildRequest
	11, // 11: fateark.proto.playerkit.PlayerKitService.SetPlayerCanBuild:input_type -> fateark.proto.playerkit.SetPlayerCanBuildRequest
	12, // 12: fateark.proto.playerkit.PlayerKitService.GetPlayerCanDig:input_type -> fateark.proto.playerkit.GetPlayerCanDigRequest
	13, // 13: fateark.proto.playerkit.PlayerKitService.SetPlayerCanDig:input_type -> fateark.proto.playerkit.SetPlayerCanDigRequest
	14, // 14: fateark.proto.playerkit.PlayerKitService.GetPlayerCanDoorsAndSwitches:input_type -> fateark.proto.playerkit.GetPlayerCanDoorsAndSwitchesRequest
	15, // 15: fateark.proto.playerkit.PlayerKitService.SetPlayerCanDoorsAndSwitches:input_type -> fateark.proto.playerkit.SetPlayerCanDoorsAndSwitchesRequest
	16, // 16: fateark.proto.playerkit.PlayerKitService.GetPlayerCanOpenContainers:input_type -> fateark.proto.playerkit.GetPlayerCanOpenContainersRequest
	17, // 17: fateark.proto.playerkit.PlayerKitService.SetPlayerCanOpenContainers:input_type -> fateark.proto.playerkit.SetPlayerCanOpenContainersRequest
	18, // 18: fateark.proto.playerkit.PlayerKitService.GetPlayerCanAttackPlayers:input_type -> fateark.proto.playerkit.GetPlayerCanAttackPlayersRequest
	19, // 19: fateark.proto.playerkit.PlayerKitService.SetPlayerCanAttackPlayers:input_type -> fateark.proto.playerkit.SetPlayerCanAttackPlayersRequest
	20, // 20: fateark.proto.playerkit.PlayerKitService.GetPlayerCanAttackMobs:input_type -> fateark.proto.playerkit.GetPlayerCanAttackMobsRequest
	21, // 21: fateark.proto.playerkit.PlayerKitService.SetPlayerCanAttackMobs:input_type -> fateark.proto.playerkit.SetPlayerCanAttackMobsRequest
	22, // 22: fateark.proto.playerkit.PlayerKitService.GetPlayerCanOperatorCommands:input_type -> fateark.proto.playerkit.GetPlayerCanOperatorCommandsRequest
	23, // 23: fateark.proto.playerkit.PlayerKitService.SetPlayerCanOperatorCommands:input_type -> fateark.proto.playerkit.SetPlayerCanOperatorCommandsRequest
	24, // 24: fateark.proto.playerkit.PlayerKitService.GetPlayerCanTeleport:input_type -> fateark.proto.playerkit.GetPlayerCanTeleportRequest
	25, // 25: fateark.proto.playerkit.PlayerKitService.SetPlayerCanTeleport:input_type -> fateark.proto.playerkit.SetPlayerCanTeleportRequest
	26, // 26: fateark.proto.playerkit.PlayerKitService.GetPlayerStatusInvulnerable:input_type -> fateark.proto.playerkit.GetPlayerStatusInvulnerableRequest
	27, // 27: fateark.proto.playerkit.PlayerKitService.GetPlayerStatusFlying:input_type -> fateark.proto.playerkit.GetPlayerStatusFlyingRequest
	28, // 28: fateark.proto.playerkit.PlayerKitService.GetPlayerStatusMayFly:input_type -> fateark.proto.playerkit.GetPlayerStatusMayFlyRequest
	29, // 29: fateark.proto.playerkit.PlayerKitService.GetPlayerDeviceID:input_type -> fateark.proto.playerkit.GetPlayerDeviceIDRequest
	30, // 30: fateark.proto.playerkit.PlayerKitService.GetPlayerEntityRuntimeID:input_type -> fateark.proto.playerkit.GetPlayerEntityRuntimeIDRequest
	31, // 31: fateark.proto.playerkit.PlayerKitService.GetPlayerEntityMetadata:input_type -> fateark.proto.playerkit.GetPlayerEntityMetadataRequest
	32, // 32: fateark.proto.playerkit.PlayerKitService.GetPlayerIsOP:input_type -> fateark.proto.playerkit.GetPlayerIsOPRequest
	33, // 33: fateark.proto.playerkit.PlayerKitService.GetPlayerOnline:input_type -> fateark.proto.playerkit.GetPlayerOnlineRequest
	34, // 34: fateark.proto.playerkit.PlayerKitService.SendPlayerChat:input_type -> fateark.proto.playerkit.SendPlayerChatRequest
	35, // 35: fateark.proto.playerkit.PlayerKitService.SendPlayerRawChat:input_type -> fateark.proto.playerkit.SendPlayerRawChatRequest
	36, // 36: fateark.proto.playerkit.PlayerKitService.SendPlayerTitle:input_type -> fateark.proto.playerkit.SendPlayerTitleRequest
	37, // 37: fateark.proto.playerkit.PlayerKitService.SendPlayerActionBar:input_type -> fateark.proto.playerkit.SendPlayerActionBarRequest
	38, // 38: fateark.proto.playerkit.PlayerKitService.InterceptPlayerJustNextInput:input_type -> fateark.proto.playerkit.InterceptPlayerJustNextInputRequest
	39, // 39: fateark.proto.playerkit.PlayerKitService.GetAllOnlinePlayers:output_type -> fateark.proto.response.GeneralResponse
	39, // 40: fateark.proto.playerkit.PlayerKitService.GetPlayerByName:output_type -> fateark.proto.response.GeneralResponse
	39, // 41: fateark.proto.playerkit.PlayerKitService.GetPlayerByUUID:output_type -> fateark.proto.response.GeneralResponse
	39, // 42: fateark.proto.playerkit.PlayerKitService.ReleaseBindPlayer:output_type -> fateark.proto.response.GeneralResponse
	39, // 43: fateark.proto.playerkit.PlayerKitService.GetPlayerName:output_type -> fateark.proto.response.GeneralResponse
	40, // 44: fateark.proto.playerkit.PlayerKitService.GetPlayerEntityUniqueID:output_type -> fateark.proto.response.GeneralInt64Response
	40, // 45: fateark.proto.playerkit.PlayerKitService.GetPlayerLoginTime:output_type -> fateark.proto.response.GeneralInt64Response
	39, // 46: fateark.proto.playerkit.PlayerKitService.GetPlayerPlatformChatID:output_type -> fateark.proto.response.GeneralResponse
	41, // 47: fateark.proto.playerkit.PlayerKitService.GetPlayerBuildPlatform:output_type -> fateark.proto.response.GeneralInt32Response
	39, // 48: fateark.proto.playerkit.PlayerKitService.GetPlayerSkinID:output_type -> fateark.proto.response.GeneralResponse
	42, // 49: fateark.proto.playerkit.PlayerKitService.GetPlayerCanBuild:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 50: fateark.proto.playerkit.PlayerKitService.SetPlayerCanBuild:output_type -> fateark.proto.response.GeneralResponse
	42, // 51: fateark.proto.playerkit.PlayerKitService.GetPlayerCanDig:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 52: fateark.proto.playerkit.PlayerKitService.SetPlayerCanDig:output_type -> fateark.proto.response.GeneralResponse
	42, // 53: fateark.proto.playerkit.PlayerKitService.GetPlayerCanDoorsAndSwitches:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 54: fateark.proto.playerkit.PlayerKitService.SetPlayerCanDoorsAndSwitches:output_type -> fateark.proto.response.GeneralResponse
	42, // 55: fateark.proto.playerkit.PlayerKitService.GetPlayerCanOpenContainers:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 56: fateark.proto.playerkit.PlayerKitService.SetPlayerCanOpenContainers:output_type -> fateark.proto.response.GeneralResponse
	42, // 57: fateark.proto.playerkit.PlayerKitService.GetPlayerCanAttackPlayers:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 58: fateark.proto.playerkit.PlayerKitService.SetPlayerCanAttackPlayers:output_type -> fateark.proto.response.GeneralResponse
	42, // 59: fateark.proto.playerkit.PlayerKitService.GetPlayerCanAttackMobs:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 60: fateark.proto.playerkit.PlayerKitService.SetPlayerCanAttackMobs:output_type -> fateark.proto.response.GeneralResponse
	42, // 61: fateark.proto.playerkit.PlayerKitService.GetPlayerCanOperatorCommands:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 62: fateark.proto.playerkit.PlayerKitService.SetPlayerCanOperatorCommands:output_type -> fateark.proto.response.GeneralResponse
	42, // 63: fateark.proto.playerkit.PlayerKitService.GetPlayerCanTeleport:output_type -> fateark.proto.response.GeneralBoolResponse
	42, // 64: fateark.proto.playerkit.PlayerKitService.SetPlayerCanTeleport:output_type -> fateark.proto.response.GeneralBoolResponse
	42, // 65: fateark.proto.playerkit.PlayerKitService.GetPlayerStatusInvulnerable:output_type -> fateark.proto.response.GeneralBoolResponse
	42, // 66: fateark.proto.playerkit.PlayerKitService.GetPlayerStatusFlying:output_type -> fateark.proto.response.GeneralBoolResponse
	42, // 67: fateark.proto.playerkit.PlayerKitService.GetPlayerStatusMayFly:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 68: fateark.proto.playerkit.PlayerKitService.GetPlayerDeviceID:output_type -> fateark.proto.response.GeneralResponse
	43, // 69: fateark.proto.playerkit.PlayerKitService.GetPlayerEntityRuntimeID:output_type -> fateark.proto.response.GeneralUint64Response
	39, // 70: fateark.proto.playerkit.PlayerKitService.GetPlayerEntityMetadata:output_type -> fateark.proto.response.GeneralResponse
	42, // 71: fateark.proto.playerkit.PlayerKitService.GetPlayerIsOP:output_type -> fateark.proto.response.GeneralBoolResponse
	42, // 72: fateark.proto.playerkit.PlayerKitService.GetPlayerOnline:output_type -> fateark.proto.response.GeneralBoolResponse
	39, // 73: fateark.proto.playerkit.PlayerKitService.SendPlayerChat:output_type -> fateark.proto.response.GeneralResponse
	39, // 74: fateark.proto.playerkit.PlayerKitService.SendPlayerRawChat:output_type -> fateark.proto.response.GeneralResponse
	39, // 75: fateark.proto.playerkit.PlayerKitService.SendPlayerTitle:output_type -> fateark.proto.response.GeneralResponse
	39, // 76: fateark.proto.playerkit.PlayerKitService.SendPlayerActionBar:output_type -> fateark.proto.response.GeneralResponse
	39, // 77: fateark.proto.playerkit.PlayerKitService.InterceptPlayerJustNextInput:output_type -> fateark.proto.response.GeneralResponse
	39, // [39:78] is the sub-list for method output_type
	0,  // [0:39] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_playerkit_proto_init() }
func file_proto_playerkit_proto_init() {
	if File_proto_playerkit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_playerkit_proto_rawDesc), len(file_proto_playerkit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_playerkit_proto_goTypes,
		DependencyIndexes: file_proto_playerkit_proto_depIdxs,
		MessageInfos:      file_proto_playerkit_proto_msgTypes,
	}.Build()
	File_proto_playerkit_proto = out.File
	file_proto_playerkit_proto_goTypes = nil
	file_proto_playerkit_proto_depIdxs = nil
}
